### ISSUE TITLE
Flora Token Economics 🌸🍯

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/flora#2]
Started discussing tradeoffs between scalability and decentralization/cryptoeconomic security in [here](https://forum.aragon.org/t/just-enough-decentralization/1262/15) in the Aragon forum. This seems very relevant to Flora as our goal is both to create a usable secure sidechain **and** to make HONEY valuable. Edited that post here to make it more relevant to Flora/HONEY:

There's 2 main ways to incentivize cryptoeconomic security in blockchains: transaction fees and block rewards. 

### Transaction Fees
Currently blockchains like Bitcoin and Ethereum use block rewards and transaction fees incentivize people to secure the network. Block rewards diminish over time, compensating the risk of being an early adopters with larger rewards. Diminishing block rewards implies that the goal for these types of networks to be sustained by transaction fees. Since space in a block is a scarce resource, lots of transactions result in high transaction fees to be included in a block. High transaction fees incentivize people to work to secure the network. Securing the network has hard capital requirements. Even though miners get paid in the network's native token, they also have to cash out that token to pay for operating expenses. This adds liquidity to the market and distributes the token among more market participants. As a network evolves, if it is successful, there will be more transactions and that will drive up transaction fees. This results in layer 1 becoming an expensive finality/settlement layer while also incentivizing applications to move towards layer 2 and/or sharding to reduce fees. More transactions lead to more fees which leads to incentives to move those transactions "up the chain" and only settle them on layer 1 occasionally. This is kind of a natural evolution of cryptoeconomics in blockchain networks.

### Block Rewards / Inflation
The other way to incentivize people is via inflation. In proof of work systems this was done through block rewards, but those block rewards diminish over time. In proof of stake systems, however, many (not all) blockchains still create block rewards. Those block rewards are not distributed to miners who have hard physical costs to secure the network. Block rewards are distributed to those who stake on the network. **This redistributes tokens to those who already have tokens.** Those stakers have no hard costs of capital. In fact, the more tokens they have staked the more tokens they will receive from inflationary block rewards. This incentivizes people to stake as many of their tokens as possible, resulting in a "rich get richer" type scenario. This is not the only problem. The other problem, is that if there are very low transaction fees and/or very large blocks, **then the only incentive is inflation.** As mentioned, inflation does not increase the value of the network, but merely redistributes the capital among current stakeholders. If the only reason to stake to the network is to get inflationary block rewards, but those rewards don't actually increase the value of the network, and the network is virtually free for users because of low/0 transaction fees.... then what is the value of the token? The value of the token then becomes worthless. No one needs it for anything. Holding it just keeps your piece of the pie, but no one needs a piece of the pie to use the network anyways, so the pie is worth nothing. Many proof of stake systems have additional features baked into their tokens that add value in other ways, but this is the dichotomy between scalability and cryptoeconomic security.

### The Dichotomy
In decentralized systems we need to verify that data is available, authentic, and received within an acceptable window of time. In order to do this we need to incentivize people to participate in that network, verifying and relaying data. This data can be stuff on IPFS, transactions sent to a DAO, or anything else on a network. The two most popular ways to do this in a trustless, decentralized, and cryptoeconomic way are Proof of Work and Proof of Stake systems as described above. There is also "proof of space-time" which IPFS uses, and many other flavors that use "proofs of X." At the end of the day though, people have to be incentivized to do stuff, and they have to prove that they did that stuff to get rewards or get punished. This makes the network run. If the network is free no one is incentivized to contribute, but if the network is too costly no one will want to use it. 

> note: Chris Burniske and Ryan Selkis talk about it in depth in [this episode](https://www.pscp.tv/w/1lPKqegBqENKb) of Unqualified Opinions

**Comment by onbjerg** [comment]
Closed as Flora is now configuration/notes on setting up an Arachain validator
